name: create-html-and-publish
on: [push]

jobs:
   create-html:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: convert to html
          run: |
             sudo apt-get install asciidoctor
             asciidoctor -R . -D . -v '**/*.adoc'

        - name: set up ssh key
          run: |
             echo '${{ secrets.DAVIDBARNHART_COM_SSH_PUBLIC }}' > ssh_key
             chmod 600 ssh_key
             ls -laht
             
        - name: upload to davidbarnhart.com
          run: |
             sudo apt-get install rsync
             rsync --exclude '*.adoc' -avz -e "ssh -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" index.html david@davidbarnhart.com:/data/davidbarnhart.com/www/
