name: create-html-and-publish
on: [push]

jobs:
   create-html:
      runs-on: ubuntu-latest
      steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: convert to html
          run: |
             sudo apt-get install asciidoctor
             asciidoctor -R . -D . '**/*.adoc'
             echo 'done'
